project:
  type: website
  output-dir: "."

website: 
  title: "Owen Ellick"
  navbar:
    pinned: true
    left:
      - text: Project
        href: project.qmd
      - text: Blog
        href: blog-listing.qmd
      - text: Python Data Analysis
        menu: 
          - text: Python Basics with ipynb
            href: basic-python-intro.ipynb
          - text: Pyhton Basics with qmd
            href: danl-210-quarto-py-only.qmd
  page-footer: 
    center: "Powered with GitHub and Quarto<br>Â© Owen Ellick, 2023"

format:
  html:
    theme: 
      light: flatly
      dark: darkly
    mainfont: system-ui; 
    highlight-style: atom-one
    css: styles.css
    toc: false
    include-after-body: target_blank.html
    
